export type Product = {
  id: string;
  name: string;
  brand?: string;
  variant?: string;
  genericName?: string;
  category?: string;
  categories?: string[];
  barcode: string;
  unitQuantity?: number;
  measurement?: string;
  unit?: string;
  color?: string;
  art?: "can" | "box" | "roll";
  packCount?: number;
  quantityText?: string;
  servingSize?: string;
  productType?: string;
  image?: string;
  source: string;
  sourceProductId?: string;
  isSeeded: boolean;
  history: number[];
};
export type SeededProduct = Product & {
  brand: string;
  unit: string;
  unitQuantity: number;
  measurement: string;
  category: string;
  art: "can" | "box" | "roll";
};
export type Retailer = {
  id: string;
  name: string;
  color: string;
  loyalty?: string;
  online: boolean;
  deliveryPence: number;
  deliveryNote?: string;
};
export type Offer = {
  id: string;
  productId: string;
  retailerId: string;
  title: string;
  packSize: number;
  pricePence: number;
  provider?: string;
  retailerProductId?: string;
  productUrl?: string;
  loyaltyPricePence?: number;
  loyaltyProgramme?: string;
  availability?: "in_stock" | "out_of_stock" | "unknown";
  retrievedAt?: string;
  isLive?: boolean;
  loyalty?: string;
};
export type LiveOffer = Offer & {
  provider: string;
  retailerProductId: string;
  availability: "in_stock" | "out_of_stock" | "unknown";
  retrievedAt: string;
  isLive: true;
};
export type Comparison = {
  retailer: Retailer;
  items: { offer: Offer; count: number }[];
  units: number;
  totalPence: number;
  unitPence: number;
  excess: number;
};
export type StashItem = {
  productId: string;
  current: number;
  target: number;
  monthly: number;
  maximum: number;
  alertPence: number;
  alertEnabled: boolean;
};
